
ingredients_examples = [
        'Salt',
        'Pepper',
        'Olive oil',
        'Butter',
        'Garlic',
        'Onion',
        'Tomato',
        'Chicken',
        'Beef',
        'Pork',
        'Eggs',
        'Milk',
        'Flour',
        'Sugar',
        'Bread',
        'Potato',
        'Rice',
        'Pasta',
        'Cheese',
        'Yogurt',
        'Lemon',
        'Honey',
        'Vinegar',
        'Mayonnaise',
        'Mustard',
        'Ketchup',
        'Soy sauce',
        'Worcestershire sauce',
        'Lettuce',
        'Cucumber',
        'Carrot',
        'Celery',
        'Bell pepper',
        'Mushroom',
        'Green beans',
        'Broccoli',
        'Cauliflower',
        'Zucchini',
        'Spinach',
        'Parsley',
        'Basil',
        'Thyme',
        'Rosemary',
        'Oregano',
        'Bay leaves',
        'Cinnamon',
        'Nutmeg',
        'Vanilla extract',
        'Lime',
        'Ginger',
        'Coconut milk',
        'Cilantro',
        'Curry powder',
        'Paprika',
        'Chili powder',
        'Cumin',
        'Coriander',
        ]

recipes_examples = {
    'SPO': {
        'name': 'Spaghetti Bolognese',
        'ingredients': ['Pasta', 'Ground beef', 'Tomato', 'Onion', 'Garlic', 'Olive oil'],
        'time': '45',
    },
    'OML': {
        'name': 'Omelette',
        'ingredients': ['Eggs', 'Butter', 'Salt', 'Pepper'],
        'time': '15',
    },
    'CTP': {
        'name': 'Chicken Tacos',
        'ingredients': ['Chicken', 'Tortillas', 'Lettuce', 'Tomato', 'Onion', 'Cilantro'],
        'time': '30',
    },
    'PBR': {
        'name': 'Potato Salad',
        'ingredients': ['Potato', 'Mayonnaise', 'Mustard', 'Onion', 'Celery', 'Salt', 'Pepper'],
        'time': '20',
    },
    'CTM': {
        'name': 'Chicken Tikka Masala',
        'ingredients': ['Chicken', 'Tomato', 'Onion', 'Garlic', 'Ginger', 'Cream', 'Spices'],
        'time': '60',
    },
    'BFC': {
        'name': 'Beef Stroganoff',
        'ingredients': ['Beef', 'Mushroom', 'Onion', 'Sour cream', 'Flour', 'Butter'],
        'time': '45',
    },
    'SCS': {
        'name': 'Scrambled Eggs',
        'ingredients': ['Eggs', 'Milk', 'Salt', 'Pepper'],
        'time': '10',
    },
    'GCR': {
        'name': 'Grilled Cheese Sandwich',
        'ingredients': ['Bread', 'Cheese', 'Butter'],
        'time': '10',
    },
    'FGS': {
        'name': 'French Toast',
        'ingredients': ['Bread', 'Eggs', 'Milk', 'Cinnamon'],
        'time': '15',
    },
    'CCH': {
        'name': 'Classic Caesar Salad',
        'ingredients': ['Romaine lettuce', 'Caesar dressing', 'Parmesan cheese', 'Croutons'],
        'time': '10',
    },
}
